import { useMemo, useState } from 'react';
import { countries } from '../data/countries';
import { products } from '../data/products';
import { currencies, paymentMethods } from '../data/paymentMethods';
import type { DealData } from '../types/deal';
import { Header } from './Header';

const steps = ['Контрагент и страна','Товар','Расчеты','Проверка данных'];
const requiredByStep: Record<number,(keyof DealData)[]> = { 0:['destinationCountry','counterpartyName','counterpartyCountry'], 1:['productCategory','productName','value','currency'], 2:['paymentMethod','paymentCurrency','payerBank','recipientBank'], 3:[] };

export function DealForm({ deal, setDeal, onSubmit, onHome, onDemo }:{deal:DealData;setDeal:(deal:DealData)=>void;onSubmit:()=>void;onHome:()=>void;onDemo:()=>void}) {
  const [step,setStep]=useState(0); const [errors,setErrors]=useState<string[]>([]); const [checking,setChecking]=useState(false);
  const update = <K extends keyof DealData>(key:K,value:DealData[K])=>setDeal({...deal,[key]:value});
  const validate=()=>{ const missing=requiredByStep[step].filter(k=>!String(deal[k])); if(step===2&&deal.intermediaryBank&&!deal.intermediaryBankName) missing.push('intermediaryBankName'); if(step===2&&deal.transit==='yes'&&!deal.transitCountry) missing.push('transitCountry'); if(step===2&&deal.endUserKnown==='yes'&&!deal.endUser) missing.push('endUser'); setErrors(missing as string[]); return !missing.length; };
  const next=()=>{if(validate()) {setErrors([]);setStep(Math.min(3,step+1));window.scrollTo({top:0,behavior:'smooth'});}};
  const countryName=useMemo(()=>countries.find(x=>x.code===deal.destinationCountry)?.name||'—',[deal.destinationCountry]);
  const productName=useMemo(()=>products.find(x=>x.code===deal.productCategory)?.name||'—',[deal.productCategory]);
  const paymentName=useMemo(()=>paymentMethods.find(x=>x.code===deal.paymentMethod)?.name||'—',[deal.paymentMethod]);
  const checkCounterparty=()=>{setChecking(true);setTimeout(()=>{setChecking(false);update('counterpartyChecked',true)},900)};
  return <main className="form-page"><Header onCheck={onHome} compact/>
    <div className="form-shell">
      <aside className="form-aside no-print"><button className="back-link" onClick={onHome}>← На главную</button><span className="eyebrow">Новая проверка</span><h1>Параметры<br/>сделки</h1><p>Заполните обязательные поля. Данные обрабатываются локально в браузере.</p><button className="demo-link" onClick={onDemo}>▣ &nbsp; Загрузить пример сделки</button>
        <ol>{steps.map((label,index)=><li key={label} className={index===step?'active':index<step?'done':''}><button onClick={()=>index<=step&&setStep(index)}><span>{index<step?'✓':String(index+1).padStart(2,'0')}</span>{label}</button></li>)}</ol>
      </aside>
      <section className="form-panel">
        <div className="mobile-progress"><span>Шаг {step+1} из 4</span><b>{steps[step]}</b><i style={{width:`${(step+1)*25}%`}}/></div>
        {step===0&&<><FormTitle number="01" title="Контрагент и страна" text="Укажите сторону сделки и страну назначения товара."/><div className="field-grid"><Field label="Страна назначения" required error={errors.includes('destinationCountry')}><Select value={deal.destinationCountry} onChange={v=>update('destinationCountry',v)} options={countries.map(x=>[x.code,x.name])}/></Field><Field label="Страна регистрации" required error={errors.includes('counterpartyCountry')}><Select value={deal.counterpartyCountry} onChange={v=>update('counterpartyCountry',v)} options={countries.map(x=>[x.code,x.name])}/></Field><Field wide label="Название иностранной компании" required error={errors.includes('counterpartyName')}><input value={deal.counterpartyName} onChange={e=>update('counterpartyName',e.target.value)} placeholder="Например, Shanghai Industrial Technologies Co., Ltd."/></Field><Field wide label="Регистрационный номер" hint="Необязательно"><input value={deal.registrationNumber} onChange={e=>update('registrationNumber',e.target.value)} placeholder="Введите номер, если известен"/></Field></div>
          <div className={`counterparty-check ${deal.counterpartyChecked?'success':''}`}><div><span>{deal.counterpartyChecked?'✓':'◎'}</span><div><b>{deal.counterpartyChecked?'Демонстрационная проверка завершена':'Базовая проверка контрагента'}</b><p>{deal.counterpartyChecked?'Компания идентифицирована · страна регистрации соответствует · явных рисков в демо-базе не обнаружено':'Сопоставим введенные данные с локальной демонстрационной базой.'}</p></div></div><button onClick={checkCounterparty} disabled={!deal.counterpartyName||checking}>{checking?'Проверяем…':deal.counterpartyChecked?'Проверить повторно':'Проверить контрагента'}</button><small>Демо-режим. Для промышленной версии предусмотрена интеграция с внешними источниками данных.</small></div></>}
        {step===1&&<><FormTitle number="02" title="Товар" text="Опишите оборудование и стоимость поставки."/><Field wide label="Категория товара" required error={errors.includes('productCategory')}><div className="choice-grid">{products.map(p=><button className={deal.productCategory===p.code?'selected':''} onClick={()=>update('productCategory',p.code)} key={p.code}><span>◇</span>{p.name}<i>{deal.productCategory===p.code?'✓':'→'}</i></button>)}</div></Field><div className="field-grid"><Field wide label="Наименование товара" required error={errors.includes('productName')}><input value={deal.productName} onChange={e=>update('productName',e.target.value)} placeholder="Точное коммерческое наименование"/></Field><Field label="Код ТН ВЭД" hint="Необязательно"><input value={deal.hsCode} onChange={e=>update('hsCode',e.target.value.replace(/\D/g,''))} placeholder="10 цифр"/></Field><Field label="Стоимость сделки" required error={errors.includes('value')}><div className="input-pair"><input type="number" min="0" value={deal.value} onChange={e=>update('value',e.target.value)} placeholder="0"/><select value={deal.currency} onChange={e=>update('currency',e.target.value)}>{currencies.map(x=><option key={x}>{x}</option>)}</select></div></Field></div></>}
        {step===2&&<><FormTitle number="03" title="Расчеты и дополнительные параметры" text="Опишите платежный маршрут, транзит и конечного пользователя."/><div className="field-grid"><Field wide label="Форма оплаты" required error={errors.includes('paymentMethod')}><div className="pill-grid">{paymentMethods.map(p=><button className={deal.paymentMethod===p.code?'selected':''} onClick={()=>update('paymentMethod',p.code)} key={p.code}>{p.name}</button>)}</div></Field><Field label="Валюта платежа" required><Select value={deal.paymentCurrency} onChange={v=>update('paymentCurrency',v)} options={currencies.map(x=>[x,x])}/></Field><Field label="Банк плательщика" required error={errors.includes('payerBank')}><input value={deal.payerBank} onChange={e=>update('payerBank',e.target.value)} placeholder="Название банка"/></Field><Field label="Банк получателя" required error={errors.includes('recipientBank')}><input value={deal.recipientBank} onChange={e=>update('recipientBank',e.target.value)} placeholder="Название банка"/></Field><Field label="Банк-посредник"><label className="toggle"><input type="checkbox" checked={deal.intermediaryBank} onChange={e=>update('intermediaryBank',e.target.checked)}/><span/> Участвует в расчетах</label></Field>{deal.intermediaryBank&&<Field label="Название банка-посредника" required error={errors.includes('intermediaryBankName')}><input value={deal.intermediaryBankName} onChange={e=>update('intermediaryBankName',e.target.value)} /></Field>}</div><div className="subsection"><h3>Дополнительные параметры</h3><Question label="Предполагается транзит через третью страну?" value={deal.transit} onChange={v=>update('transit',v)}/>{deal.transit==='yes'&&<Field label="Страна транзита" required error={errors.includes('transitCountry')}><Select value={deal.transitCountry} onChange={v=>update('transitCountry',v)} options={countries.filter(x=>x.code!==deal.destinationCountry).map(x=>[x.code,x.name])}/></Field>}<Question label="Известен конечный пользователь товара?" value={deal.endUserKnown} onChange={v=>update('endUserKnown',v)}/>{deal.endUserKnown==='yes'&&<Field label="Конечный пользователь" required error={errors.includes('endUser')}><input value={deal.endUser} onChange={e=>update('endUser',e.target.value)} /></Field>}<div className="question"><span>Товар предназначен для гражданского использования?</span><div>{[['yes','Да'],['no','Нет'],['unsure','Не уверен']].map(x=><button key={x[0]} className={deal.civilianUse===x[0]?'selected':''} onClick={()=>update('civilianUse',x[0] as DealData['civilianUse'])}>{x[1]}</button>)}</div></div></div></>}
        {step===3&&<><FormTitle number="04" title="Проверьте данные" text="Перед запуском анализа убедитесь, что параметры указаны верно."/><div className="review-card"><span>Параметры сделки</span><Review label="Страна назначения" value={countryName}/><Review label="Товар" value={`${productName} · ${deal.productName}`}/><Review label="Стоимость" value={`${Number(deal.value).toLocaleString('ru-RU')} ${deal.currency}`}/><Review label="Способ оплаты" value={`${paymentName} · ${deal.paymentCurrency}`}/><Review label="Контрагент" value={deal.counterpartyName}/><Review label="Конечный пользователь" value={deal.endUser||'Не указан'}/></div><div className="demo-disclaimer">ⓘ Анализ выполняется по локальной демонстрационной базе и не является юридическим заключением.</div></>}
        {errors.length>0&&<div className="error-summary">Заполните выделенные обязательные поля, чтобы продолжить.</div>}
        <div className="form-actions no-print"><button className="button button-ghost" disabled={step===0} onClick={()=>setStep(step-1)}>← Назад</button>{step<3?<button className="button button-primary" onClick={next}>Продолжить →</button>:<button className="button button-primary launch" onClick={onSubmit}>Запустить проверку ↗</button>}</div>
      </section>
    </div>
  </main>;
}

function FormTitle({number,title,text}:{number:string;title:string;text:string}){return <div className="form-title"><span>{number}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
function Field({label,hint,required,error,wide,children}:{label:string;hint?:string;required?:boolean;error?:boolean;wide?:boolean;children:React.ReactNode}){return <label className={`field ${wide?'wide':''} ${error?'invalid':''}`}><span>{label}{required&&<b>*</b>}{hint&&<em>{hint}</em>}</span>{children}{error&&<small>Заполните это поле</small>}</label>}
function Select({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:string[][]}){return <select value={value} onChange={e=>onChange(e.target.value)}><option value="">Выберите вариант</option>{options.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select>}
function Question({label,value,onChange}:{label:string;value:'yes'|'no';onChange:(v:'yes'|'no')=>void}){return <div className="question"><span>{label}</span><div><button className={value==='yes'?'selected':''} onClick={()=>onChange('yes')}>Да</button><button className={value==='no'?'selected':''} onClick={()=>onChange('no')}>Нет</button></div></div>}
function Review({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
