import { useState } from 'react';
import { countryByCode } from '../data/countries';
import { productByCode } from '../data/products';
import { paymentByCode } from '../data/paymentMethods';
import type { AnalysisResult, DealData, RiskLevel } from '../types/deal';
import { Header } from './Header';

const labels:Record<RiskLevel,string>={low:'Низкий',medium:'Средний',high:'Высокий'};
export function Report({deal,result,onNew,onHome}:{deal:DealData;result:AnalysisResult;onNew:()=>void;onHome:()=>void}) {
  const [checked,setChecked]=useState<number[]>([]);
  const toggle=(i:number)=>setChecked(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i]);
  return <main className="report-page"><Header compact onCheck={onNew}/><section className="report-head"><button className="back-link no-print" onClick={onHome}>← На главную</button><div className="report-kicker"><span>Результат проверки сделки</span><b>ID проверки: {result.id}</b><b>{result.date}</b></div><div className="report-hero"><div><span className="muted-label">Общий уровень риска</span><h1>{labels[result.level]} риск</h1><p>Предварительная оценка по демонстрационной модели</p></div><div className={`large-score ${result.level}`}><strong>{result.totalScore}</strong><span>/ 100</span></div></div><div className="risk-scale"><i style={{width:`${result.totalScore}%`}}/><span>Низкий</span><span>Средний</span><span>Высокий</span></div><div className="report-actions no-print"><button className="button button-light" onClick={()=>window.print()}>⇩ Распечатать / сохранить в PDF</button><button className="button button-primary" onClick={onNew}>Новая проверка →</button></div></section>
    <div className="report-body">
      <section className="deal-strip"><div><span>Страна</span><b>{countryByCode(deal.destinationCountry)?.name}</b></div><div><span>Товар</span><b>{productByCode(deal.productCategory)?.name}</b></div><div><span>Стоимость</span><b>{Number(deal.value).toLocaleString('ru-RU')} {deal.currency}</b></div><div><span>Расчеты</span><b>{paymentByCode(deal.paymentMethod)?.name} · {deal.paymentCurrency}</b></div><div><span>Контрагент</span><b>{deal.counterpartyName}</b></div></section>
      <Section title="Карта рисков" eyebrow="Структура оценки"><div className="risk-cards">{result.categories.map(cat=><article key={cat.key}><div><span className="risk-icon">{cat.icon}</span><i className={cat.level}/></div><h3>{cat.label}</h3><b>{labels[cat.level]}</b><p>{cat.note}</p><div className="dots">{[0,1,2].map(x=><i className={x<(cat.level==='low'?1:cat.level==='medium'?2:3)?cat.level:''} key={x}/>)}</div></article>)}</div></Section>
      <Section title="Что требует внимания" eyebrow={`${result.findings.length} выявленных факторов`}><div className="findings">{result.findings.map((f,i)=><article className={f.status} key={i}><span>{f.status==='success'?'✓':'!'}</span><div><h3>{f.title}</h3><p>{f.description}</p><b>Рекомендация</b><p>{f.recommendation}</p></div></article>)}</div></Section>
      <div className="report-columns"><Section title="Чек-лист документов" eyebrow={`${checked.length} из ${result.documents.length} отмечено`}><p className="section-intro">Перед заключением сделки рекомендуется проверить наличие:</p><div className="checklist">{result.documents.map((doc,i)=><label key={doc} className={checked.includes(i)?'checked':''}><input type="checkbox" checked={checked.includes(i)} onChange={()=>toggle(i)}/><span>{checked.includes(i)?'✓':''}</span>{doc}</label>)}</div></Section><Section title="На что обратить внимание" eyebrow="Нормативная рамка"><div className="regulations">{result.regulations.map((r,i)=><div key={r}><span>{String(i+1).padStart(2,'0')}</span><p>{r}</p></div>)}</div><small>Перечень сформирован в демонстрационных целях и не является исчерпывающим.</small></Section></div>
      <Section title="Рекомендуемые следующие шаги" eyebrow="План действий"><ol className="recommendations">{result.recommendations.map((r,i)=><li key={r}><span>{String(i+1).padStart(2,'0')}</span><p>{r}</p></li>)}</ol></Section>
      <section className="disclaimer"><span>i</span><p><b>Важная информация</b>«Экспортный патруль» — демонстрационный прототип информационно-аналитического сервиса. Результат автоматизированной проверки носит информационный характер, формируется на основе демонстрационной базы и не является юридическим заключением. Перед совершением внешнеторговой сделки рекомендуется провести проверку с использованием актуальных официальных источников и при необходимости обратиться к специалисту.</p></section>
    </div><footer><span>© 2026 Экспортный патруль</span><span>{result.id} · {result.date}</span></footer>
  </main>;
}
function Section({title,eyebrow,children}:{title:string;eyebrow:string;children:React.ReactNode}){return <section className="report-section"><div className="section-title"><span>{eyebrow}</span><h2>{title}</h2></div>{children}</section>}
